//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KegokProj.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class FullParams
    {
        public int ID { get; set; }
        public Nullable<int> TowerID { get; set; }
        public int Day { get; set; }
        public int Month { get; set; }
        public int Year { get; set; }
        public int Hour { get; set; }
        public int Minute { get; set; }
        public int Second { get; set; }
        public string PhaseA_CPD { get; set; }
        public string PhaseA_BC { get; set; }
        public string PhaseB_CPD { get; set; }
        public string PhaseB_BC { get; set; }
        public string PhaseC_CPD { get; set; }
        public string PhaseC_BC { get; set; }
        public string Humidity { get; set; }
        public string Temp { get; set; }
        public string Amplitude_fluct_X { get; set; }
        public string Freq_fluct_X { get; set; }
        public string Amplitude_fluct_Y { get; set; }
        public string Freq_fluct_Y { get; set; }
        public string Amplitude_fluct_Z { get; set; }
        public string Freq_fluct_Z { get; set; }
        public string Angle_XZ { get; set; }
        public string Angle_YZ { get; set; }
        public long Abs_time { get; set; }
    
        public virtual Towers Towers { get; set; }
    }
}
